### PR TITLE
Fix problems surrounding logging

### LINKED ISSUE #25: Logger does not properly work for non-boolean values
Constructing the boolean log entry first (and at construction) means the subdir used will be permanently allocated to type boolean.

Fix: move the construction of the log entries to after the first call of update(T) so that only the log entry fitting for generic T attempts to allocate that subdir.

Also surrounding logging:
- values are being repeated to the log even if they don't change-- will quickly run out of space on the roborio if attempting to log dozens of double-precision floats every 20 milliseconds
- order of startup logging in HighLevelLogger doesn't make sense-- it ends up always throwing the (harmless) warning for already having started the logger
- probably just remove the entire warning for the logger already being started, it does nothing useful

### PR DESCRIPTION
**Pull request by tandej**
Closes #25

### CODE REVIEW

File: src/main/java/org/chsrobotics/lib/telemetry/Logger.java [hunk 1]
```diff
@@ -16,108 +16,91 @@
...
+import edu.wpi.first.networktables.NetworkTableInstance;
 import edu.wpi.first.util.datalog.BooleanLogEntry;
 import edu.wpi.first.util.datalog.DataLog;
 import edu.wpi.first.util.datalog.DoubleLogEntry;
 import edu.wpi.first.util.datalog.StringLogEntry;
-import edu.wpi.first.wpilibj.shuffleboard.Shuffleboard;
 
 /**
- * Utility to streamline publishing data to NetworkTables and save it to an on-robot log file.
+ * Utility to streamline publishing data to NetworkTables and saving it to an on-robot log file.
```
Comment (elliotnash) [inline src/main/java/org/chsrobotics/lib/telemetry/Logger.java:27]: and saving it to on robot log files

**Review by elliotnash — CHANGES_REQUESTED** [review]
